[package]
name = "winit_web_example"
version = "0.1.0"
edition = "2024"
authors = ["Saad Moazzam"]

[dependencies]
winit = "0.30.9"
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3.77", features = ["HtmlCanvasElement"]}
console_error_panic_hook = "0.1.7"

[lib]
crate-type = ["cdylib", "rlib"]
